### ISSUE TITLE
查看应用的部署历史没有实现

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#40]
@uniseraph

**Comment by cbcbbcbc** [comment]
DEBU[0403] HGETALL content: &redis.StringStringMapCmd{baseCmd:redis.baseCmd{_args:[]interface {}{"hgetall", "redis.uid.session.a2fb3790-6929-11e7-9f06-542696d68b2d"}, err:error(nil), _readTimeout:(*time.Duration)(nil)}, val:map[string]string{"uid":"59686a220c7a15d9439f5afb", "roleSet":"4"}} 
INFO[0403] SessionContent: map[string]string{"uid":"59686a220c7a15d9439f5afb", "roleSet":"4"} 
DEBU[0403] getApplication::符合条件的deployment有0个           
2017/07/15 15:41:26 http: panic serving 127.0.0.1:53838: result argument must be a slice address
goroutine 170 [running]:
net/http.(*conn).serve.func1(0xc420470fa0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0x163b9e0, 0xc42077b3d0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/zanecloud/apiserver/vendor/gopkg.in/mgo%2ev2.(*Iter).All(0xc4207222d0, 0x162ae00, 0xc420337560, 0xc420683620, 0xc420337560)
	/work/go/src/github.com/zanecloud/apiserver/vendor/gopkg.in/mgo.v2/session.go:3791 +0xc8
github.com/zanecloud/apiserver/vendor/gopkg.in/mgo%2ev2.(*Query).All(0xc420686000, 0x162ae00, 0xc420337560, 0xc420337560, 0xc420686000)
	/work/go/src/github.com/zanecloud/apiserver/vendor/gopkg.in/mgo.v2/session.go:3818 +0x4d
github.com/zanecloud/apiserver/handlers.getApplicationHistory.func1(0xc420481110)
	/work/go/src/github.com/zanecloud/apiserver/handlers/application_handler.go:245 +0x404
github.com/zanecloud/apiserver/utils.GetMgoCollections(0x1a952e0, 0xc420480f90, 0x1a94620, 0xc42043cb60, 0xc4206837c8, 0x1, 0x1, 0xc420683820)
	/work/go/src/github.com/zanecloud/apiserver/utils/utils.go:105 +0x3ff
github.com/zanecloud/apiserver/handlers.getApplicationHistory(0x1a952e0, 0xc420480f90, 0x1a94620, 0xc42043cb60, 0xc420767b00)
	/work/go/src/github.com/zanecloud/apiserver/handlers/application_handler.go:276 +0x305
github.com/zanecloud/apiserver/handlers.checkUserPermission.func1(0x1a952e0, 0xc42037a480, 0x1a94620, 0xc42043cb60, 0xc420767b00)
	/work/go/src/github.com/zanecloud/apiserver/handlers/main_handler.go:288 +0xa56
github.com/zanecloud/apiserver/handlers.SetupPrimaryRouter.func1(0x1a94620, 0xc42043cb60, 0xc420767b00)
	/work/go/src/github.com/zanecloud/apiserver/handlers/main_handler.go:348 +0x31c
